<?php
	$b_table="yp_admin,yp_admingroup,yp_adv,yp_config,yp_fankui,yp_file,yp_index,yp_lanmu,yp_liuyan,yp_lyreply,yp_nav,yp_news,yp_newspic,yp_order,yp_user,yp_winmsg,yp_youlink,yp_zhaoshang";
	$tb[yp_admin]=1;
$tb[yp_admingroup]=1;
$tb[yp_adv]=1;
$tb[yp_config]=1;
$tb[yp_fankui]=1;
$tb[yp_file]=1;
$tb[yp_index]=1;
$tb[yp_lanmu]=1;
$tb[yp_liuyan]=1;
$tb[yp_lyreply]=1;
$tb[yp_nav]=1;
$tb[yp_news]=1;
$tb[yp_newspic]=1;
$tb[yp_order]=1;
$tb[yp_user]=1;
$tb[yp_winmsg]=1;
$tb[yp_youlink]=1;
$tb[yp_zhaoshang]=1;

	$b_baktype=0;
	$b_filesize=300;
	$b_bakline=500;
	$b_autoauf=1;
	$b_dbname="youpin";
	$b_stru=1;
	$b_strufour=0;
	$b_dbchar="auto";
	$b_beover=0;
	$b_insertf="replace";
	$b_autofield=",,";
	?>